// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anime_hashtags.sql

package query

import (
	"context"

	"github.com/lib/pq"
)

const createAnimeHashtag = `-- name: CreateAnimeHashtag :one
INSERT INTO anime_hashtags (
    anime_id,
    hashtag,
    created_at,
    updated_at
) VALUES (
    $1, $2, NOW(), NOW()
) RETURNING id, anime_id, hashtag, sort_number, created_at, updated_at
`

type CreateAnimeHashtagParams struct {
	AnimeID int64  `db:"anime_id"`
	Hashtag string `db:"hashtag"`
}

func (q *Queries) CreateAnimeHashtag(ctx context.Context, arg CreateAnimeHashtagParams) (AnimeHashtag, error) {
	row := q.db.QueryRowContext(ctx, createAnimeHashtag, arg.AnimeID, arg.Hashtag)
	var i AnimeHashtag
	err := row.Scan(
		&i.ID,
		&i.AnimeID,
		&i.Hashtag,
		&i.SortNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnimeHashtag = `-- name: DeleteAnimeHashtag :exec
DELETE FROM anime_hashtags
WHERE id = $1
`

func (q *Queries) DeleteAnimeHashtag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAnimeHashtag, id)
	return err
}

const listAnimeHashtagsByAnimeIDs = `-- name: ListAnimeHashtagsByAnimeIDs :many
SELECT id, anime_id, hashtag, sort_number, created_at, updated_at FROM anime_hashtags
WHERE anime_id = ANY($1::bigint[])
ORDER BY anime_id, sort_number, hashtag
`

func (q *Queries) ListAnimeHashtagsByAnimeIDs(ctx context.Context, dollar_1 []int64) ([]AnimeHashtag, error) {
	rows, err := q.db.QueryContext(ctx, listAnimeHashtagsByAnimeIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnimeHashtag{}
	for rows.Next() {
		var i AnimeHashtag
		if err := rows.Scan(
			&i.ID,
			&i.AnimeID,
			&i.Hashtag,
			&i.SortNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
