// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: password_reset_tokens.sql

package query

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id,
    token_digest,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, token_digest, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID      int64     `db:"user_id"`
	TokenDigest string    `db:"token_digest"`
	ExpiresAt   time.Time `db:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken, arg.UserID, arg.TokenDigest, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < $1 OR used_at < $1
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens, expiresAt)
	return err
}

const deleteUnusedPasswordResetTokensByUserID = `-- name: DeleteUnusedPasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens
WHERE user_id = $1
AND used_at IS NULL
`

func (q *Queries) DeleteUnusedPasswordResetTokensByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedPasswordResetTokensByUserID, userID)
	return err
}

const getPasswordResetTokenByDigest = `-- name: GetPasswordResetTokenByDigest :one
SELECT id, user_id, token_digest, expires_at, used_at, created_at FROM password_reset_tokens
WHERE token_digest = $1
AND used_at IS NULL
AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetPasswordResetTokenByDigest(ctx context.Context, tokenDigest string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByDigest, tokenDigest)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenDigest,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokensByUserID = `-- name: GetPasswordResetTokensByUserID :many
SELECT id, user_id, token_digest, expires_at, used_at, created_at FROM password_reset_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPasswordResetTokensByUserID(ctx context.Context, userID int64) ([]PasswordResetToken, error) {
	rows, err := q.db.QueryContext(ctx, getPasswordResetTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenDigest,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const invalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE user_id = $1
AND used_at IS NULL
`

func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, invalidateUserPasswordResetTokens, userID)
	return err
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenAsUsed, id)
	return err
}
