FROM node:12.16.1-alpine

LABEL maintainer="https://annict.com/@shimbaco" \
    description="A platform for anime addicts."

RUN apk update && \
    apk add -t \
    build-dependencies \
    build-base \
    git \
    python

ENV PATH=./node_modules/.bin/:$PATH \
    NODE_ENV=development

WORKDIR /workspace/

COPY package.json yarn.lock ./
RUN yarn install && \
    yarn cache clean

EXPOSE 8080
