FROM node:16.14.2-buster-slim

LABEL maintainer="https://annict.jp/@shimbaco" \
  description="A platform for anime addicts."

# Bashを使用する
SHELL ["/bin/bash", "-c"]

RUN true \
  && apt update \
  && apt install -y --no-install-recommends \
  build-essential \
  git \
  python

ENV PATH=./node_modules/.bin/:$PATH \
  NODE_ENV=development

WORKDIR /workspace/

COPY package.json package-lock.json ./
RUN npm install && \
  npm cache clean --force

EXPOSE 8080
