# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Canary::Types::InputObjects::EpisodeOrder`.
# Please instead update this file by running `bin/tapioca dsl Canary::Types::InputObjects::EpisodeOrder`.


class Canary::Types::InputObjects::EpisodeOrder
  sig { returns(::String) }
  def direction; end

  sig { returns(::String) }
  def field; end
end
