eslint:
  enabled: false
  config_file: .eslintrc
  version: 5.16.0

jshint:
  enabled: false

ruby:
  config_file: .rubocop.yml

sass-lint:
  enabled: true
  config_file: .sass-lint.yml

scss:
  enabled: false
