files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  id-name-format:
    - 1
    - convention: hyphenatedbem
  leading-zero:
    - 1
    - include: true
  nesting-depth:
    - 1
    - max-depth: 5
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  quotes:
    - 2
    - style: double
