ARG RUBY_VERSION="3.1.4"
ARG BUNDLER_VERSION="2.3.12"
ARG NODE_VERSION="16.14.2"
ARG YARN_VERSION="1.22.21"

FROM node:${NODE_VERSION}-bullseye-slim AS node
ARG YARN_VERSION
RUN yarn set version ${YARN_VERSION}

FROM ruby:${RUBY_VERSION}-slim-bullseye

RUN \
  apt update && \
  apt dist-upgrade -yq && \
  apt install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    # PostgreSQLやYarnのインストールに必要
    gnupg

# PostgreSQLのセットアップ
RUN \
  curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  echo "deb https://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
  apt update && \
  apt install -y --no-install-recommends \
    libpq-dev \
    postgresql-client-14

ARG YARN_VERSION
COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /.yarn/releases/yarn-${YARN_VERSION}.cjs /usr/local/bin/yarn

RUN gem install bundler -v "${BUNDLER_VERSION}"

WORKDIR /app

CMD ["bash"]
