# frozen_string_literal: true

# standard:disable Layout/ExtraSpacing, Layout/LineLength
match "/db",                                    via: :get,    as: :db_root,                     to: "v4/db/home#show"
match "/db/activities",                         via: :get,    as: :db_activity_list,            to: "v4/db/activities#index"
match "/db/casts/:id",                          via: :delete, as: :db_cast_detail,              to: "v4/db/casts#destroy"
match "/db/casts/:id",                          via: :patch,                                    to: "v4/db/casts#update"
match "/db/casts/:id/edit",                     via: :get,    as: :db_edit_cast,                to: "v4/db/casts#edit"
match "/db/casts/:id/publishing",               via: :delete, as: :db_cast_publishing,          to: "v4/db/cast_publishings#destroy"
match "/db/casts/:id/publishing",               via: :post,                                     to: "v4/db/cast_publishings#create"
match "/db/channel_groups",                     via: :get,    as: :db_channel_group_list,       to: "v4/db/channel_groups#index"
match "/db/channel_groups",                     via: :post,                                     to: "v4/db/channel_groups#create"
match "/db/channel_groups/:id",                 via: :delete, as: :db_channel_group_detail,     to: "v4/db/channel_groups#destroy"
match "/db/channel_groups/:id",                 via: :patch,                                    to: "v4/db/channel_groups#update"
match "/db/channel_groups/:id/edit",            via: :get,    as: :db_edit_channel_group,       to: "v4/db/channel_groups#edit"
match "/db/channel_groups/:id/publishing",      via: :delete, as: :db_channel_group_publishing, to: "v4/db/channel_group_publishings#destroy"
match "/db/channel_groups/:id/publishing",      via: :post,                                     to: "v4/db/channel_group_publishings#create"
match "/db/channel_groups/new",                 via: :get,    as: :db_new_channel_group,        to: "v4/db/channel_groups#new"
match "/db/channels",                           via: :get,    as: :db_channel_list,             to: "v4/db/channels#index"
match "/db/channels",                           via: :post,                                     to: "v4/db/channels#create"
match "/db/channels/:id",                       via: :delete, as: :db_channel_detail,           to: "v4/db/channels#destroy"
match "/db/channels/:id",                       via: :patch,                                    to: "v4/db/channels#update"
match "/db/channels/:id/edit",                  via: :get,    as: :db_edit_channel,             to: "v4/db/channels#edit"
match "/db/channels/:id/publishing",            via: :delete, as: :db_channel_publishing,       to: "v4/db/channel_publishings#destroy"
match "/db/channels/:id/publishing",            via: :post,                                     to: "v4/db/channel_publishings#create"
match "/db/channels/new",                       via: :get,    as: :db_new_channel,              to: "v4/db/channels#new"
match "/db/characters",                         via: :get,    as: :db_character_list,           to: "v4/db/characters#index"
match "/db/characters",                         via: :post,                                     to: "v4/db/characters#create"
match "/db/characters/:id",                     via: :delete, as: :db_character_detail,         to: "v4/db/characters#destroy"
match "/db/characters/:id",                     via: :patch,                                    to: "v4/db/characters#update"
match "/db/characters/:id/edit",                via: :get,    as: :db_edit_character,           to: "v4/db/characters#edit"
match "/db/characters/:id/publishing",          via: :delete, as: :db_character_publishing,     to: "v4/db/character_publishings#destroy"
match "/db/characters/:id/publishing",          via: :post,                                     to: "v4/db/character_publishings#create"
match "/db/characters/new",                     via: :get,    as: :db_new_character,            to: "v4/db/characters#new"
match "/db/episodes/:id",                       via: :delete, as: :db_episode_detail,           to: "v4/db/episodes#destroy"
match "/db/episodes/:id",                       via: :patch,                                    to: "v4/db/episodes#update"
match "/db/episodes/:id/edit",                  via: :get,    as: :db_edit_episode,             to: "v4/db/episodes#edit"
match "/db/episodes/:id/publishing",            via: :delete, as: :db_episode_publishing,       to: "v4/db/episode_publishings#destroy"
match "/db/episodes/:id/publishing",            via: :post,                                     to: "v4/db/episode_publishings#create"
match "/db/organizations",                      via: :get,    as: :db_organization_list,        to: "v4/db/organizations#index"
match "/db/organizations",                      via: :post,                                     to: "v4/db/organizations#create"
match "/db/organizations/:id",                  via: :delete, as: :db_organization_detail,      to: "v4/db/organizations#destroy"
match "/db/organizations/:id",                  via: :patch,                                    to: "v4/db/organizations#update"
match "/db/organizations/:id/edit",             via: :get,    as: :db_edit_organization,        to: "v4/db/organizations#edit"
match "/db/organizations/:id/publishing",       via: :delete, as: :db_organization_publishing,  to: "v4/db/organization_publishings#destroy"
match "/db/organizations/:id/publishing",       via: :post,                                     to: "v4/db/organization_publishings#create"
match "/db/organizations/new",                  via: :get,    as: :db_new_organization,         to: "v4/db/organizations#new"
match "/db/people",                             via: :get,    as: :db_person_list,              to: "v4/db/people#index"
match "/db/people",                             via: :post,                                     to: "v4/db/people#create"
match "/db/people/:id",                         via: :delete, as: :db_person_detail,            to: "v4/db/people#destroy"
match "/db/people/:id",                         via: :patch,                                    to: "v4/db/people#update"
match "/db/people/:id/edit",                    via: :get,    as: :db_edit_person,              to: "v4/db/people#edit"
match "/db/people/:id/publishing",              via: :delete, as: :db_person_publishing,        to: "v4/db/person_publishings#destroy"
match "/db/people/:id/publishing",              via: :post,                                     to: "v4/db/person_publishings#create"
match "/db/people/new",                         via: :get,    as: :db_new_person,               to: "v4/db/people#new"
match "/db/programs/:id",                       via: :delete, as: :db_program_detail,           to: "v4/db/programs#destroy"
match "/db/programs/:id",                       via: :patch,                                    to: "v4/db/programs#update"
match "/db/programs/:id/edit",                  via: :get,    as: :db_edit_program,             to: "v4/db/programs#edit"
match "/db/programs/:id/publishing",            via: :delete, as: :db_program_publishing,       to: "v4/db/program_publishings#destroy"
match "/db/programs/:id/publishing",            via: :post,                                     to: "v4/db/program_publishings#create"
match "/db/search",                             via: :get,    as: :db_search,                   to: "v4/db/searches#show"
match "/db/series",                             via: :get,    as: :db_series_list,              to: "v4/db/series#index"
match "/db/series",                             via: :post,                                     to: "v4/db/series#create"
match "/db/series/:id",                         via: :delete, as: :db_series_detail,            to: "v4/db/series#destroy"
match "/db/series/:id",                         via: :patch,                                    to: "v4/db/series#update"
match "/db/series/:id/edit",                    via: :get,    as: :db_edit_series,              to: "v4/db/series#edit"
match "/db/series/:id/publishing",              via: :delete, as: :db_series_publishing,        to: "v4/db/series_publishings#destroy"
match "/db/series/:id/publishing",              via: :post,                                     to: "v4/db/series_publishings#create"
match "/db/series/:series_id/series_works",     via: :get,    as: :db_series_work_list,         to: "v4/db/series_works#index"
match "/db/series/:series_id/series_works",     via: :post,                                     to: "v4/db/series_works#create"
match "/db/series/:series_id/series_works/new", via: :get,    as: :db_new_series_work,          to: "v4/db/series_works#new"
match "/db/series/new",                         via: :get,    as: :db_new_series,               to: "v4/db/series#new"
match "/db/series_works/:id",                   via: :delete, as: :db_series_work_detail,       to: "v4/db/series_works#destroy"
match "/db/series_works/:id",                   via: :patch,                                    to: "v4/db/series_works#update"
match "/db/series_works/:id/edit",              via: :get,    as: :db_edit_series_work,         to: "v4/db/series_works#edit"
match "/db/series_works/:id/publishing",        via: :delete, as: :db_series_work_publishing,   to: "v4/db/series_work_publishings#destroy"
match "/db/series_works/:id/publishing",        via: :post,                                     to: "v4/db/series_work_publishings#create"
match "/db/slots/:id",                          via: :delete, as: :db_slot_detail,              to: "v4/db/slots#destroy"
match "/db/slots/:id",                          via: :patch,                                    to: "v4/db/slots#update"
match "/db/slots/:id/edit",                     via: :get,    as: :db_edit_slot,                to: "v4/db/slots#edit"
match "/db/slots/:id/publishing",               via: :delete, as: :db_slot_publishing,          to: "v4/db/slot_publishings#destroy"
match "/db/slots/:id/publishing",               via: :post,                                     to: "v4/db/slot_publishings#create"
match "/db/staffs/:id",                         via: :delete, as: :db_staff_detail,             to: "v4/db/staffs#destroy"
match "/db/staffs/:id",                         via: :patch,                                    to: "v4/db/staffs#update"
match "/db/staffs/:id/edit",                    via: :get,    as: :db_edit_staff,               to: "v4/db/staffs#edit"
match "/db/staffs/:id/publishing",              via: :delete, as: :db_staff_publishing,         to: "v4/db/staff_publishings#destroy"
match "/db/staffs/:id/publishing",              via: :post,                                     to: "v4/db/staff_publishings#create"
match "/db/trailers/:id",                       via: :delete, as: :db_trailer_detail,           to: "v4/db/trailers#destroy"
match "/db/trailers/:id",                       via: :patch,                                    to: "v4/db/trailers#update"
match "/db/trailers/:id/edit",                  via: :get,    as: :db_edit_trailer,             to: "v4/db/trailers#edit"
match "/db/trailers/:id/publishing",            via: :delete, as: :db_trailer_publishing,       to: "v4/db/trailer_publishings#destroy"
match "/db/trailers/:id/publishing",            via: :post,                                     to: "v4/db/trailer_publishings#create"
match "/db/works",                              via: :get,    as: :db_work_list,                to: "v4/db/works#index"
match "/db/works",                              via: :post,                                     to: "v4/db/works#create"
match "/db/works/:id",                          via: :delete, as: :db_work_detail,              to: "v4/db/works#destroy"
match "/db/works/:id",                          via: :patch,                                    to: "v4/db/works#update"
match "/db/works/:id/edit",                     via: :get,    as: :db_edit_work,                to: "v4/db/works#edit"
match "/db/works/:id/publishing",               via: :delete, as: :db_work_publishing,          to: "v4/db/work_publishings#destroy"
match "/db/works/:id/publishing",               via: :post,                                     to: "v4/db/work_publishings#create"
match "/db/works/:work_id/casts",               via: :get,    as: :db_cast_list,                to: "v4/db/casts#index"
match "/db/works/:work_id/casts",               via: :post,                                     to: "v4/db/casts#create"
match "/db/works/:work_id/casts/new",           via: :get,    as: :db_new_cast,                 to: "v4/db/casts#new"
match "/db/works/:work_id/episodes",            via: :get,    as: :db_episode_list,             to: "v4/db/episodes#index"
match "/db/works/:work_id/episodes",            via: :post,                                     to: "v4/db/episodes#create"
match "/db/works/:work_id/episodes/new",        via: :get,    as: :db_new_episode,              to: "v4/db/episodes#new"
match "/db/works/:work_id/image",               via: :get,    as: :db_work_image_detail,        to: "v4/db/work_images#show"
match "/db/works/:work_id/image",               via: :patch,                                    to: "v4/db/work_images#update"
match "/db/works/:work_id/image",               via: :post,                                     to: "v4/db/work_images#create"
match "/db/works/:work_id/programs",            via: :get,    as: :db_program_list,             to: "v4/db/programs#index"
match "/db/works/:work_id/programs",            via: :post,                                     to: "v4/db/programs#create"
match "/db/works/:work_id/programs/new",        via: :get,    as: :db_new_program,              to: "v4/db/programs#new"
match "/db/works/:work_id/slots",               via: :get,    as: :db_slot_list,                to: "v4/db/slots#index"
match "/db/works/:work_id/slots",               via: :post,                                     to: "v4/db/slots#create"
match "/db/works/:work_id/slots/new",           via: :get,    as: :db_new_slot,                 to: "v4/db/slots#new"
match "/db/works/:work_id/staffs",              via: :get,    as: :db_staff_list,               to: "v4/db/staffs#index"
match "/db/works/:work_id/staffs",              via: :post,                                     to: "v4/db/staffs#create"
match "/db/works/:work_id/staffs/new",          via: :get,    as: :db_new_staff,                to: "v4/db/staffs#new"
match "/db/works/:work_id/trailers",            via: :get,    as: :db_trailer_list,             to: "v4/db/trailers#index"
match "/db/works/:work_id/trailers",            via: :post,                                     to: "v4/db/trailers#create"
match "/db/works/:work_id/trailers/new",        via: :get,    as: :db_new_trailer,              to: "v4/db/trailers#new"
match "/db/works/new",                          via: :get,    as: :db_new_work,                 to: "v4/db/works#new"
# standard:enable Layout/ExtraSpacing, Layout/LineLength
