# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday-multipart` gem.
# Please instead update this file by running `bin/tapioca gem faraday-multipart`.


# pkg:gem/faraday-multipart#lib/faraday/multipart/version.rb:3
module Faraday; end

# pkg:gem/faraday-multipart#lib/faraday/multipart.rb:18
Faraday::CompositeReadIO = Faraday::Multipart::CompositeReadIO

# Aliases for Faraday v1, these are all deprecated and will be removed in v2 of this middleware
#
# pkg:gem/faraday-multipart#lib/faraday/multipart.rb:15
Faraday::FilePart = Multipart::Post::UploadIO

# Main Faraday::Multipart module.
# Rubocop doesn't seem to understand that this is an extension to the
# Multipart module, so let's add a nodoc
#
# pkg:gem/faraday-multipart#lib/faraday/multipart/version.rb:5
module Faraday::Multipart
  class << self
    # pkg:gem/faraday-multipart#lib/faraday/multipart/version.rb:8
    def multipart_post_version; end
  end
end

# Similar to, but not compatible with CompositeReadIO provided by the
# multipart-post gem.
# https://github.com/nicksieger/multipart-post/blob/master/lib/composite_io.rb
#
# pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:67
class Faraday::Multipart::CompositeReadIO
  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:68
  def initialize(*parts); end

  # Close each of the IOs.
  #
  # @return [void]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:111
  def close; end

  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:115
  def ensure_open_and_readable; end

  # @return [Integer] sum of the lengths of all the parts
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:75
  def length; end

  # Read from IOs in order until `length` bytes have been received.
  #
  # @param length [Integer, nil]
  # @param outbuf [String, nil]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:91
  def read(length = T.unsafe(nil), outbuf = T.unsafe(nil)); end

  # Rewind each of the IOs and reset the index to 0.
  #
  # @return [void]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:82
  def rewind; end

  private

  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:125
  def advance_io; end

  # pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:121
  def current_io; end
end

# pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:55
Faraday::Multipart::FilePart = Multipart::Post::UploadIO

# Middleware for supporting multi-part requests.
#
# pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:8
class Faraday::Multipart::Middleware < ::Faraday::Middleware
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:12
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # Checks for files in the payload, otherwise leaves everything untouched.
  #
  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:20
  def call(env); end

  private

  # @param env [Faraday::Env]
  # @param params [Hash]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:76
  def create_multipart(env, params); end

  # Returns true if obj is an enumerable with values that are multipart.
  #
  # @param obj [Object]
  # @return [Boolean]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:65
  def has_multipart?(obj); end

  # @param env [Faraday::Env]
  # @yield [request_body] Body of the request
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:34
  def match_content_type(env); end

  # Determines and provides the multipart mime type for the request.
  #
  # @return [String] the multipart mime type
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:125
  def mime_type; end

  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:88
  def part(boundary, key, value); end

  # @param params [Hash]
  # @param prefix [String]
  # @param pieces [Array]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:104
  def process_params(params, prefix = T.unsafe(nil), pieces = T.unsafe(nil), &block); end

  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:44
  def process_request?(env); end

  # @param env [Faraday::Env]
  #
  # @return [String]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:55
  def request_type(env); end

  # @return [String]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:97
  def unique_boundary; end
end

# pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:9
Faraday::Multipart::Middleware::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# pkg:gem/faraday-multipart#lib/faraday/multipart/middleware.rb:10
Faraday::Multipart::Middleware::DEFAULT_BOUNDARY_PREFIX = T.let(T.unsafe(nil), String)

# Multipart value used to POST data with a content type.
#
# pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:6
class Faraday::Multipart::ParamPart
  # @param value [String] Uploaded content as a String.
  # @param content_type [String] String content type of the value.
  # @param content_id [String] Optional String of this value's Content-ID.
  #
  # @return [Faraday::ParamPart]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:12
  def initialize(value, content_type, content_id = T.unsafe(nil)); end

  # The value's content ID, if given.
  #
  # @return [String, nil]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:52
  def content_id; end

  # The value's content type.
  #
  # @return [String]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:47
  def content_type; end

  # Returns a Hash of String key/value pairs.
  #
  # @return [Hash]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:32
  def headers; end

  # Converts this value to a form part.
  #
  # @param boundary [String] String multipart boundary that must not exist in
  #   the content exactly.
  # @param key [String] String key name for this value.
  #
  # @return [Faraday::Parts::Part]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:25
  def to_part(boundary, key); end

  # The content to upload.
  #
  # @return [String]
  #
  # pkg:gem/faraday-multipart#lib/faraday/multipart/param_part.rb:42
  def value; end
end

# pkg:gem/faraday-multipart#lib/faraday/multipart/file_part.rb:56
Faraday::Multipart::Parts = Multipart::Post::Parts

# pkg:gem/faraday-multipart#lib/faraday/multipart/version.rb:6
Faraday::Multipart::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/faraday-multipart#lib/faraday/multipart.rb:16
Faraday::ParamPart = Faraday::Multipart::ParamPart

# pkg:gem/faraday-multipart#lib/faraday/multipart.rb:17
Faraday::Parts = Multipart::Post::Parts

# multipart-post v2.2.0 introduces a new class hierarchy for classes like Parts and UploadIO
# For backwards compatibility, detect the gem version and use the right class
#
# pkg:gem/faraday-multipart#lib/faraday/multipart.rb:21
Faraday::UploadIO = Multipart::Post::UploadIO
