name: Formatter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - run: pnpm run fmt:check
